server:
  port: 8082

spring:
  datasource:
    url: ${INVENTORY_DB_URL:jdbc:postgresql://localhost:5434/inventory}
    username: ${INVENTORY_DB_USER:inventory}
    password: ${INVENTORY_DB_PASSWORD:inventory}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}
