server:
  port: 8083

spring:
  datasource:
    url: ${ORDER_DB_URL:jdbc:postgresql://localhost:5435/orders}
    username: ${ORDER_DB_USER:orders}
    password: ${ORDER_DB_PASSWORD:orders}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}
